# Generated by Django 4.1.2 on 2022-11-01 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_hm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hm',
        ),
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
