# Generated by Django 4.1.2 on 2022-11-05 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0004_alter_task_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=512)),
                ('creator', models.CharField(blank=True, max_length=64, null=True)),
                ('time', models.DateField(default=datetime.date(2022, 11, 5))),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DateField(default=datetime.date(2022, 11, 5)),
        ),
    ]
