# Generated by Django 4.1.2 on 2022-11-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0005_reminder_alter_task_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='importance',
        ),
    ]
