# Generated by Django 4.1.2 on 2022-11-06 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0006_remove_task_importance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev', models.TextField(max_length=10000)),
                ('creator', models.CharField(blank=True, max_length=64, null=True)),
                ('time', models.DateField(default=datetime.date(2022, 11, 6))),
                ('topic', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.DateField(default=datetime.date(2022, 11, 6)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DateField(default=datetime.date(2022, 11, 6)),
        ),
    ]
