# Generated by Django 4.1.2 on 2022-11-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0009_user_time_zone_alter_reminder_time_alter_review_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DateTimeField(default=None),
        ),
    ]
